---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# mapcan

`mapcan` is an R package that provides convenient tools for plotting a variety of Canadian maps with the `ggplot2` package. 

# Using mapcan

`mapcan` data are best utilized with `ggplot2`

```{r echo = TRUE, warning = FALSE, message = FALSE}
library(mapcan)
library(ggplot2)
library(tidyverse)
library(paletteer)
```


## Tile grid map of Canadian federal electoral ridings

```{r echo = FALSE}
federal_riding_bins <- mapcan::federal_riding_bins

federal_riding_bins$pr_alpha <- factor(federal_riding_bins$pr_alpha, levels = c("BC", "AB", "SK", "MB", "ON", "QC", "NL", "NB", "PE", "NS"))

ggplot(federal_riding_bins[federal_riding_bins$representation_order == 2013, ], aes(x = y, y = x, fill = pr_alpha)) +
  geom_raster() +
  geom_tile(colour = "white", size = 1.5, fill = NA) +
  paletteer::scale_fill_paletteer_d("ggthemes", "tableau_greenorange12") +
  coord_fixed() +
  scale_y_reverse() +
  theme_light()  +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  guides(fill = guide_legend(keywidth = 0.6, keyheight = 0.3,
                             nrow = 1, title = NULL)) +
  ggtitle("Canadian federal electoral ridings (2013 representation order)")
```

```{r}
sum(table(federal_election_results_2015$pr_alpha))
table(federal_riding_bins$pr_alpha)
```

```{r }
ggplot(federal_riding_bins[federal_riding_bins$representation_order == 2003, ], aes(x = y, y = x, fill = pr_alpha)) +
  geom_raster() +
  geom_tile(colour = "white", size = 1.5, fill = NA) +
  paletteer::scale_fill_paletteer_d("ggthemes", "tableau_greenorange12") +
  coord_fixed() +
  scale_y_reverse() +
  theme_light()  +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(), 
        axis.title = element_blank(),
        legend.position = "bottom") +
  guides(fill = guide_legend(keywidth = 0.6, keyheight = 0.3,
                             nrow = 1, title = NULL)) +
  ggtitle("Canadian federal electoral ridings (2003 representation order)")
```

```{r include = FALSE, echo = FALSE}
paletteer::palettes_d_names
paletteer::paletteer_d("ggsci", "category10_d3")
```

## 2015 Canadian federal election results

```{r echo = FALSE}
federal_ridings <- mapcan::federal_ridings

federal_ridings <- left_join(federal_ridings, riding_info, by = c("riding_code" = "riding_code"))

ggplot(federal_ridings, aes(long, lat, group = group, fill = party)) +
  geom_polygon() +
  scale_fill_manual(values = c("darkslategray3", "dodgerblue3", "green", "firebrick1", "darkorange1")) +
  theme_light() +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(), 
        axis.title = element_blank(),
        legend.title = element_blank()) +
  coord_fixed()
```



## Provincial/territorial cartogram

```{r echo = FALSE}
provinces_territories_carto_df <- mapcan::provinces_territories_carto_df

ggplot(provinces_territories_carto_df, aes(long, lat, group = group, fill = population)) +
  geom_polygon() +
  theme_light() +
  scale_fill_gradient(low = "indianred1", high = "darkred") + 
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(), 
        axis.title = element_blank(),
        legend.title = element_blank()) +
  coord_fixed() +
  ggtitle("Provincial/territorial cartogram\n(distorted by population)")

provinces_noterr_carto_df <- mapcan::provinces_noterr_carto_df

ggplot(provinces_noterr_carto_df, aes(long, lat, group = group, fill = population)) +
  geom_polygon() +
  theme_light() +
  scale_fill_gradient(low = "indianred1", high = "darkred") + 
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(), 
        axis.title = element_blank(),
        legend.title = element_blank()) +
  coord_fixed() +
  ggtitle("Provincial/territorial cartogram\n(distorted by population),\nterritories excluded")

```
## Census division cartograms
```{r echo = FALSE}
census_divisions_2016_carto_df <- mapcan::census_divisions_2016_carto_df

ggplot(census_divisions_2016_carto_df, aes(long, lat, group = group, fill = population_2016)) +
  geom_polygon() +
  theme_light() +
  scale_fill_gradient(low = "darkslategray", high = "darkslategray3", 
                      labels = scales::comma,
                      breaks = seq(0, 2731571, 500000)) + 
  guides(fill = guide_colorbar(barwidth = 1, barheight = 8, label.hjust = 1.2)) +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(), 
        axis.title = element_blank(),
        legend.title = element_blank()) +
  coord_fixed() +
  ggtitle("2016 census divisions cartogram (distorted by population)") 

census_divisions_2016_noterr_carto_df <- mapcan::census_divisions_2016_noterr_carto_df

ggplot(census_divisions_2016_noterr_carto_df, aes(long, lat, group = group, fill = population_2016)) +
  geom_polygon() +
  theme_light() +
  scale_fill_gradient(low = "darkslategray", high = "darkslategray3", 
                      labels = scales::comma,
                      breaks = seq(0, 2731571, 500000)) + 
  guides(fill = guide_colorbar(barwidth = 1, barheight = 8, label.hjust = 1.2)) +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(), 
        axis.title = element_blank(),
        legend.title = element_blank()) +
  coord_fixed() +
  ggtitle("2016 census divisions cartogram (distorted by population), territories excluded") 
```

